### ISSUE TITLE
Check layout of driver-edit.xml

### ISSUE THREAD

**Issue by glebfox** [ilushaaa/jmix-hw-working-with-files#1]
* Right click on Screen Caption > Analyze Layout

Result: 
```
[ERROR] Container 'HBoxLayoutImpl', nested component 'VBoxLayoutImpl'
Nested component has relative width 100.0% inside container with undefined width

[WARN] Container 'HBoxLayoutImpl', nested component 'VBoxLayoutImpl'
Nested component has align MIDDLE_CENTER inside container with undefined size
```

**Comment by ilushaaa** [comment]
I fixed the layout and warnings has gone. 
But now I can't set driver's photo relative to the middle of the buttons. Will try again later.

**Comment by ilushaaa** [comment]
Remove unnecessary hbox, set width for vbox and align for image. Now the image is centered.
